In [31]:
import pandas as pd

In [32]:
df = pd.read_csv("nba_games_2.csv", index_col=0)

In [33]:
df

,mp,mp.1,fg,fga,fg%,3p,3pa,3p%,ft,fta,...,tov%_max_opp,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won
0,240,240,38,72,0.528,16,37,0.432,18,21,...,26.2,26.8,155,123,MIA,107,1,2023,2022-11-07,True
1,240,240,40,84,0.476,14,39,0.359,13,15,...,41.0,37.3,160,121,POR,110,0,2023,2022-11-07,False
2,240,240,41,78,0.526,8,24,0.333,15,19,...,28.6,41.1,250,125,DAL,90,1,2023,2022-12-14,True
3,240,240,29,74,0.392,13,38,0.342,19,26,...,12.6,33.0,183,110,CLE,105,0,2023,2022-12-14,False
4,240,240,39,81,0.481,6,20,0.300,14,18,...,22.8,29.0,178,111,DAL,95,1,2016,2015-12-09,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22629,240,240,43,92,0.467,12,34,0.353,12,19,...,51.5,33.0,200,112,MIN,117,0,2024,2023-11-10,False
22630,240,240,41,85,0.482,9,26,0.346,26,30,...,27.7,27.1,150,126,MIA,106,1,2020,2020-09-19,True
22631,240,240,33,85,0.388,12,44,0.273,28,34,...,51.5,36.2,141,114,BOS,117,0,2020,2020-09-19,False
22632,240,240,42,82,0.512,12,27,0.444,12,19,...,53.2,28.0,146,126,TOR,121,1,2024,2023-11-24,False
22633,240,240,44,83,0.530,13,39,0.333,20,27,...,25.0,34.3,195,136,CHI,108,0,2024,2023-11-24,True

In [34]:
df = df.sort_values("date")
df = df.reset_index(drop=True) # resets the index to the sorted list, but drops the aditional column with the old indexes
del df["mp.1"]
del df["mp_opp.1"]
del df["index_opp"]

In [35]:
def add_target(team):
    team["target"] = team["won"].shift(-1) # takes in a team's games and makes a column if the team won their next game
    return team

df = df.groupby("team", group_keys = False).apply(add_target) # if group_keys is not false there will be unnecessary indexes

In [36]:
# After splitting data frame using groupby, we can use data frame for each team
df[df["team"] == "GSW"]

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
4,240,41,96,0.427,9,30,0.300,20,22,0.909,...,38.9,201,120,NOP,95,0,2016,2015-10-27,True,True
53,240,43,93,0.462,9,26,0.346,17,25,0.680,...,37.5,151,118,HOU,92,1,2016,2015-10-30,True,True
71,240,46,84,0.548,17,30,0.567,25,35,0.714,...,36.1,218,131,NOP,120,1,2016,2015-10-31,True,True
94,240,43,84,0.512,11,25,0.440,22,30,0.733,...,44.3,106,126,MEM,69,0,2016,2015-11-02,True,True
128,240,39,85,0.459,10,26,0.385,24,31,0.774,...,32.9,250,122,LAC,108,0,2016,2015-11-04,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22519,240,38,85,0.447,14,36,0.389,20,26,0.769,...,28.1,152,121,MIN,114,1,2024,2024-03-24,False,True
22555,240,47,85,0.553,13,38,0.342,6,10,0.600,...,58.0,222,129,MIA,92,1,2024,2024-03-26,True,True
22572,240,40,90,0.444,10,34,0.294,11,13,0.846,...,34.3,151,121,ORL,93,1,2024,2024-03-27,True,True
22605,240,48,89,0.539,11,32,0.344,8,9,0.889,...,37.4,159,130,CHO,97,1,2024,2024-03-29,True,True
22620,240,45,92,0.489,16,39,0.410,11,13,0.846,...,41.5,158,130,SAS,113,1,2024,2024-03-31,True,NaN

In [37]:
df["target"][pd.isnull(df["target"])] = 2 # N/As become 2s

/var/folders/73/sdx5t33n3mbc72lvs97v4kcc0000gn/T/ipykernel_17573/1784734554.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["target"][pd.isnull(df["target"])] = 2 # N/As become 2s

In [38]:
df["target"] = df["target"].astype(int, errors = "ignore") # convert target from boolean to int without errors

In [39]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240,37,96,0.385,12,29,0.414,20,26,0.769,...,33.8,258,121,ATL,94,1,2016,2015-10-27,True,1
1,240,37,82,0.451,8,27,0.296,12,15,0.800,...,23.6,132,104,DET,106,0,2016,2015-10-27,False,1
2,240,37,87,0.425,7,19,0.368,16,23,0.696,...,29.0,138,105,CLE,95,0,2016,2015-10-27,True,1
3,240,38,94,0.404,9,29,0.310,10,17,0.588,...,34.6,162,104,CHI,97,1,2016,2015-10-27,False,1
4,240,41,96,0.427,9,30,0.300,20,22,0.909,...,38.9,201,120,NOP,95,0,2016,2015-10-27,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22629,240,45,84,0.536,20,40,0.500,17,23,0.739,...,28.5,144,143,UTA,106,0,2024,2024-03-31,True,2
22630,240,48,93,0.516,24,47,0.511,5,9,0.556,...,28.3,208,138,HOU,107,1,2024,2024-03-31,True,2
22631,240,38,81,0.469,11,37,0.297,14,21,0.667,...,36.2,146,115,CHI,109,0,2024,2024-03-31,False,2
22632,240,50,87,0.575,21,33,0.636,9,13,0.692,...,33.0,189,143,CLE,101,0,2024,2024-03-31,True,2
22633,240,43,75,0.573,14,29,0.483,30,34,0.882,...,25.9,158,144,CHO,118,1,2024,2024-03-31,True,2

In [40]:
df["won"].value_counts()

won
True     11317
False    11317
Name: count, dtype: int64

In [41]:
df["target"].value_counts()

target
1    11303
0    11301
2       30
Name: count, dtype: int64

In [42]:
# Get rid of nulls for ml
nulls = pd.isnull(df)

In [43]:
nulls = nulls.sum() # sometimes rerun all cells to fix bugs
nulls = nulls[nulls > 0] # returns only columns where there are more than one nulls
valid_columns = df.columns[~df.columns.isin(nulls.index)] # not in nulls
nulls

+/-             22634
mp_max          22634
mp_max.1        22634
+/-_opp         22634
mp_max_opp      22634
mp_max_opp.1    22634
dtype: int64

In [44]:
df = df[valid_columns].copy()

In [45]:
# code to find null games so that I can modify csv file
# teams = df["team"][pd.isnull(df["+/-_max"])]
# dates = df["date"][pd.isnull(df["+/-_max"])]
# null_games = pd.concat([teams, dates], axis=1)
# null_games

# Used the original csv file to make a new csv file with some fixes

In [46]:
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,240,37,96,0.385,12,29,0.414,20,26,0.769,...,33.8,258,121,ATL,94,1,2016,2015-10-27,True,1
1,240,37,82,0.451,8,27,0.296,12,15,0.800,...,23.6,132,104,DET,106,0,2016,2015-10-27,False,1
2,240,37,87,0.425,7,19,0.368,16,23,0.696,...,29.0,138,105,CLE,95,0,2016,2015-10-27,True,1
3,240,38,94,0.404,9,29,0.310,10,17,0.588,...,34.6,162,104,CHI,97,1,2016,2015-10-27,False,1
4,240,41,96,0.427,9,30,0.300,20,22,0.909,...,38.9,201,120,NOP,95,0,2016,2015-10-27,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22629,240,45,84,0.536,20,40,0.500,17,23,0.739,...,28.5,144,143,UTA,106,0,2024,2024-03-31,True,2
22630,240,48,93,0.516,24,47,0.511,5,9,0.556,...,28.3,208,138,HOU,107,1,2024,2024-03-31,True,2
22631,240,38,81,0.469,11,37,0.297,14,21,0.667,...,36.2,146,115,CHI,109,0,2024,2024-03-31,False,2
22632,240,50,87,0.575,21,33,0.636,9,13,0.692,...,33.0,189,143,CLE,101,0,2024,2024-03-31,True,2
22633,240,43,75,0.573,14,29,0.483,30,34,0.882,...,25.9,158,144,CHO,118,1,2024,2024-03-31,True,2

In [47]:
from sklearn.model_selection import TimeSeriesSplit # helps make predictions taking time into account
from sklearn.feature_selection import SequentialFeatureSelector # removes data from a dataset to improve speed
from sklearn.linear_model import RidgeClassifier # complex correlation model

rr = RidgeClassifier(alpha=1) # https://towardsdatascience.com/the-power-of-ridge-regression-4281852a64d6

# we can't do cross validation because you can't use future data to predict past data.
split = TimeSeriesSplit(n_splits=3) # split data into 3 sections?

# will choose which columns to train model on
sfs = SequentialFeatureSelector(rr, n_features_to_select=30, direction="forward", cv=split)

In [48]:
# preparing columns for scaling, so the data can be easily trained on.
# scaling means to fit data into a range
removed_columns = ["season", "date", "won", "target", "team", "team_opp"]
selected_columns = df.columns[~df.columns.isin(removed_columns)]

In [49]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[selected_columns] = scaler.fit_transform(df[selected_columns])
df

,mp,fg,fga,fg%,3p,3pa,3p%,ft,fta,ft%,...,usg%_max_opp,ortg_max_opp,drtg_max_opp,team_opp,total_opp,home_opp,season,date,won,target
0,0.0,0.391304,0.529412,0.277512,0.413793,0.378788,0.491686,0.441860,0.396825,0.730455,...,0.151282,0.800948,0.500000,ATL,0.267857,1.0,2016,2015-10-27,True,1
1,0.0,0.391304,0.323529,0.435407,0.275862,0.348485,0.351544,0.255814,0.222222,0.766628,...,0.020513,0.203791,0.306818,DET,0.375000,0.0,2016,2015-10-27,False,1
2,0.0,0.391304,0.397059,0.373206,0.241379,0.227273,0.437055,0.348837,0.349206,0.645274,...,0.089744,0.232227,0.318182,CLE,0.276786,0.0,2016,2015-10-27,True,1
3,0.0,0.413043,0.500000,0.322967,0.310345,0.378788,0.368171,0.209302,0.253968,0.519253,...,0.161538,0.345972,0.306818,CHI,0.294643,1.0,2016,2015-10-27,False,1
4,0.0,0.478261,0.529412,0.377990,0.310345,0.393939,0.356295,0.441860,0.333333,0.893816,...,0.216667,0.530806,0.488636,NOP,0.276786,0.0,2016,2015-10-27,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22629,0.0,0.565217,0.352941,0.638756,0.689655,0.545455,0.593824,0.372093,0.349206,0.695449,...,0.083333,0.260664,0.750000,UTA,0.375000,0.0,2024,2024-03-31,True,2
22630,0.0,0.630435,0.485294,0.590909,0.827586,0.651515,0.606888,0.093023,0.126984,0.481914,...,0.080769,0.563981,0.693182,HOU,0.383929,1.0,2024,2024-03-31,True,2
22631,0.0,0.413043,0.308824,0.478469,0.379310,0.500000,0.352732,0.302326,0.317460,0.611435,...,0.182051,0.270142,0.431818,CHI,0.401786,0.0,2024,2024-03-31,False,2
22632,0.0,0.673913,0.397059,0.732057,0.724138,0.439394,0.755344,0.186047,0.190476,0.640607,...,0.141026,0.473934,0.750000,CLE,0.330357,0.0,2024,2024-03-31,True,2
22633,0.0,0.521739,0.220588,0.727273,0.482759,0.378788,0.573634,0.674419,0.523810,0.862310,...,0.050000,0.327014,0.761364,CHO,0.482143,1.0,2024,2024-03-31,True,2

In [50]:
# select 30 best features for predicting target
sfs.fit(df[selected_columns], df["target"])

SequentialFeatureSelector(cv=TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None),
                          estimator=RidgeClassifier(alpha=1),
                          n_features_to_select=30)

In [51]:
# get the best columns from the SequentialFeatureSelector
predictors = list(selected_columns[sfs.get_support()]) # get support will be true if that columns was chosen by the sfs
predictors

['fg',
 'fga',
 'fg%',
 '3p%',
 'ft%',
 'orb%',
 'trb%',
 'usg%',
 'pts_max',
 '+/-_max',
 'tov%_max',
 'home',
 '3p_opp',
 'ft%_opp',
 'pts_opp',
 'drb%_opp',
 'trb%_opp',
 'ast%_opp',
 'blk%_opp',
 'usg%_opp',
 'fg_max_opp',
 'fga_max_opp',
 '3p%_max_opp',
 'ft_max_opp',
 'ft%_max_opp',
 'trb_max_opp',
 'trb%_max_opp',
 'usg%_max_opp',
 'total_opp',
 'home_opp']

In [91]:
# machine learning!
def backtest(data, model, predictors, start = 2, step = 1): # data is the data frame
    all_predictions = [] # list of dataframes, where each dataframe is the predictions for a single season
    seasons = sorted(data["season"].unique())

    for i in range(start, len(seasons), step):
        season = seasons[i]
        
        train = data[data["season"]<season]
        test = data[data["season"]==season]

        # so I had an error, where I was training the model on the test targets.
        model.fit(train[predictors], train["target"]) # .fit() is the method to train the model.

        # once model is created then make predictions
        preds = model.predict(test[predictors]) # this will try and guess whether they won their next game.
        preds = pd.Series(preds, index = test.index)

        combined = pd.concat([test["target"], preds], axis = 1)
        combined.columns = ["actual", "prediction"]

        all_predictions.append(combined)
    return pd.concat(all_predictions)

In [92]:
predictions = backtest(df, rr, predictors)
predictions

       actual  prediction
5250        0           0
5251        1           1
5252        1           0
5253        1           1
5254        0           0
...       ...         ...
22629       2           1
22630       2           1
22631       2           0
22632       2           1
22633       2           1

[17384 rows x 2 columns]

In [93]:
# accuracy of the model
from sklearn.metrics import accuracy_score

accuracy_score(predictions["actual"], predictions["prediction"])

0.5427404509894156

In [95]:
# home team based prediction accuracy
df.groupby("home").apply(lambda x: x[x["won"]==1].shape[0] / x.shape[0]) # lamda function

home
0.0    0.430061
1.0    0.569939
dtype: float64

In [ ]:
# right now the model uses the current game to predict the next game